<?xml version="1.0"?>
<package format="3">
  <name>hello_ros</name>
  <version>0.0.1</version>
  <description>Progressive ROS 2 (rclcpp) learning steps</description>
  <maintainer email="solomonxiewise@gmail.com">Solomon X.</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>example_interfaces</depend>
  <depend>geometry_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
