[raspberrypi]
pi-zero ansible_host=pi-zero.local ansible_user=pi

[nanopi]
nanopi-r2s ansible_host=nanopi-r2s ansible_user=root

[raspberrypi:vars]
ansible_become=true

[nanopi:vars]
ansible_become=false
